services:
  zoomsdk: &zoomsdk
    build: ./
    volumes:
     - .:/tmp/python-zoom-linux-sdk
    ports:
      - "3000:3000"
    environment:
      - ZOOM_APP_CLIENT_ID
      - ZOOM_APP_CLIENT_SECRET
      - MEETING_URLS