name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  
    - name: Install gdown
      run: pip install gdown
    - name: Cache extracted files
      id: cache-extract
      uses: actions/cache@v4
      with:
        path: src/zoomsdk
        key: ${{ runner.os }}-extract-${{ hashFiles('src/zoomsdk/zoom-meeting-sdk-linux_x86_64-6.2.0.1953.tar.xz') }}
    - name: Download and extract if cache miss
      if: steps.cache-extract.outputs.cache-hit != 'true'
      run: |
        gdown 1S8rIC2ejb3dUBs0qDbzRWNBnzgJRqNQv
        tar -xf zoom-meeting-sdk-linux_x86_64-6.2.0.1953.tar.xz -C src
        mv src/zoom-meeting-sdk-linux_x86_64-6.2.0.1953 src/zoomsdk
    - name: Look at files
      run: ls src/zoomsdk/*
    - name: Build docker image
      run: docker build -t zoomsdk .