name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install gdown
      run: pip install gdown

    - name: Cache extracted files
      id: cache-extract
      uses: actions/cache@v4
      with:
        path: src/zoomsdk
        key: ${{ runner.os }}-extract-zoom-meeting-sdk-linux_x86_64-6.2.0.1953.tar.xz

    - name: Download and extract if cache miss
      if: steps.cache-extract.outputs.cache-hit != 'true'
      run: |
        mkdir src/zoomsdk
        gdown 1S8rIC2ejb3dUBs0qDbzRWNBnzgJRqNQv
        tar -xf zoom-meeting-sdk-linux_x86_64-6.2.0.1953.tar.xz -C src/zoomsdk

    - name: Look at files
      run: ls src/zoomsdk/*

    - name: Cache Docker image
      id: cache-docker-image
      uses: actions/cache@v4
      with:
        path: /tmp/docker-image
        key: ${{ runner.os }}-docker-image-${{ hashFiles('Dockerfile') }}

    - name: Load cached Docker image
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: docker load < /tmp/docker-image/zoomsdk.tar

    - name: Build Docker image
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      run: |
        docker build -t zoomsdk:latest .
        mkdir -p /tmp/docker-image
        docker save zoomsdk:latest > /tmp/docker-image/zoomsdk.tar

    - name: Look at more
      run: ls .