name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add mask
      run: echo "::add-mask::${{ secrets.ZOOM_SDK_GDRIVE_ID }}"

    - name: Install gdown
      run: pip install gdown

    - name: Cache extracted files
      id: cache-extract
      uses: actions/cache@v4
      with:
        path: src/zoomsdk
        key: ${{ runner.os }}-extract-${{ secrets.ZOOM_SDK_FILENAME }}

    - name: Download and extract if cache miss
      if: steps.cache-extract.outputs.cache-hit != 'true'
      run: |
        mkdir src/zoomsdk
        gdown ${{ secrets.ZOOM_SDK_GDRIVE_ID }}
        tar -xf ${{ secrets.ZOOM_SDK_FILENAME }} -C src/zoomsdk

    - name: Look at files
      run: ls src/zoomsdk/*

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Build and cache Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: zoomsdk:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run build script in Docker container
      run: docker compose run --rm zoomsdk /bin/bash -c "source scripts/build.sh; python3 test_scripts/test.py sample_program/sample.py"

    - name: Look at more
      run: ls .